### ISSUE TITLE
Visual Editor crashes when trying to add an action

### ISSUE THREAD

**Issue by yu-tendo** [GeorgeSG/lovelace-time-picker-card#48] opened 2022-12-22 20:05 UTC
### Checklist:

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser (tried Strg+F5 several times, and deleted the history)

### The problem

The Visual editor crashes when I try to add an action. Please see the attached image -when I click on any of these entries, the popup/window closes. I don't see any error in the browser console. Some times strings are visible next to the icon -sometimes not. I cannot reproduce it.

I installed this addon through HACS. After installing it, I restarted the service and cleared the browser cache. The error occurs in Firefox and Chrome.

### Environment

- Time Picker Card 1.4.0
- HACS 1.29.0
- Firefox 108.0.1 / Chrome 108.0.5359.125 (Windows 10)
- Home Assistant 2022.12.7 (Frontend 20221213.1 - latest)

![error](https://user-images.githubusercontent.com/72860114/209217056-07aedccb-e585-421d-a674-5f87d1d8ed42.png)

**Comment by lensherm** [comment] 2023-01-03 01:05
Same here

**Comment by djtail** [comment] 2023-02-12 00:04
any update on this problem?

**Comment by timo-sztyler** [comment] 2023-02-12 09:05
I did not figure out the issue and as the developer did not react, I moved to: https://github.com/nielsfaber/scheduler-card

**Comment by GeorgeSG** [comment] 2024-11-05 20:08
Actions from editor don't work, duplicate of #57

**Closed by GeorgeSG** 2024-11-05 20:08 UTC
Labels: bug
